# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.3

EAPI=8

DESCRIPTION="Robust, Minimalist, Unbundled PKM for your favorite text-editor through the LSP"
HOMEPAGE="https://github.com/Feel-ix-343/markdown-oxide"
SRC_URI="https://github.com/Feel-ix-343/markdown-oxide/releases/download/v${PV}/${PN}-v${PV}-x86_64-unknown-linux-gnu.tar.gz -> ${P}.tar.gz"

LICENSE=""
# Dependent crate licenses
LICENSE+="
	BSD CC0-1.0 ISC MIT MPL-2.0 Unicode-DFS-2016
	|| ( Apache-2.0 Boost-1.0 )
"
SLOT="0"
KEYWORDS="~amd64"

src_unpack() {
if [[ -n ${A} ]]; then
		unpack ${A}
		mv ${WORKDIR}/markdown-oxide-v0.23.1-x86_64-unknown-linux-gnu ${WORKDIR}/${P}
	fi
}

src_compile() {
    dobin "${PN}"
}

